from environs import Env

__all__ = (
    'ADMINS_TELEGRAM_BOT_TOKEN',
    'USERS_TELEGRAM_BOT_TOKEN',
    'ADMINS_TELEGRAM_IDS',
)

env = Env()
env.read_env()

ADMINS_TELEGRAM_IDS = env.list('ADMINS_TELEGRAM_IDS', subcast=int)
USERS_TELEGRAM_BOT_TOKEN = env.str('USERS_TELEGRAM_BOT_TOKEN')
ADMINS_TELEGRAM_BOT_TOKEN = env.str('ADMINS_TELEGRAM_BOT_TOKEN')
